apiVersion: indeed.com/v1beta1
kind: RabbitMQNetworkPartition
metadata:
  name: example-rabbitmqnetworkpartition
spec:
  clusterName: myrabbitmq
  partitions:
    - - myrabbitmq-0
      - myrabbitmq-1
    - - myrabbitmq-2
  drained: []
  serviceName: myrabbitmq-svc-discovery.rabbitmq-operator.svc.cluster.local
