apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmq-operator.indeed.com
spec:
  group: indeed.com
  names:
    kind: RabbitMQ
    listKind: RabbitMQList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RabbitMQ is the Schema for the rabbitmqs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RabbitMQSpec defines the desired state of RabbitMQ
          type: object
        status:
          description: RabbitMQStatus defines the observed state of RabbitMQ
          type: object
        rabbitMQImage:
          type: string
        initContainerImage:
          type: string
        createLoadBalancer:
          type: boolean
        preserveOrphanPVCs:
          type: boolean
        replicas:
          type: number
          minimum: 0
        compute:
          properties:
            cpuRequest:
              type: string
            memory:
              type: string
        storage:
          properties:
            storageClassName:
              type: string
            limit:
              type: string
        clusterSpec:
          properties:
            highWatermarkFraction:
              type: number
              minimum: 0
              maximum: 1.0
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
