apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster_role_binding.yaml
- cluster_role.yaml
- configmap.yaml
- operator.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
- crds/indeed.com_rabbitmqnetworkpartitions_crd.yaml
- crds/indeed.com_rabbitmqs_crd.yaml
