apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-operator
  template:
    metadata:
      labels:
        name: rabbitmq-operator
    spec:
      serviceAccountName: rabbitmq-operator
      containers:
        - name: rabbitmq-operator
          image: indeedoss/rabbitmq-operator:latest
          command:
          - rabbitmq-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: logging-configuration
              mountPath: /logging-configuration
      volumes:
        - name: logging-configuration
          configMap:
            name: rabbitmq-operator-logger-configuration
